export const menuItems = [
  {
    id: 1,
    name: "Classic Burger",
    image: "/images/menu/Classic-Burger-Photoroom.png",
    price: 18,
    rating: 4.8,
    badge: "Popular",
  },
  {
    id: 2,
    name: "Cheese Burger",
    image: "/images/menu/Cheese-Burger-Photoroom.png",
    price: 22,
    rating: 4.9,
    badge: "Hot",
  },
  {
    id: 3,
    name: "Chicken Burger",
    image: "/images/menu/Chicken-Sandwich-Photoroom.png",
    price: 20,
    rating: 4.7,
    badge: "New",
  },
  {
    id: 4,
    name: "Pepper Pizza",
    image: "/images/menu/peper-pizza-Photoroom.png",
    price: 25,
    rating: 4.9,
    badge: "Best",
  },
  {
    id: 5,
    name: "Club Sandwich",
    image: "/images/menu/Club-Sandwich-Photoroom.png",
    price: 16,
    rating: 4.8,
    badge: "Chef",
  },
  {
    id: 6,
    name: "French Fries",
    image: "/images/menu/French-Fries-Photoroom copy.png",
    price: 10,
    rating: 4.7,
    badge: "Fresh",
  },
];